name = "erp-construcciones-sac"
main = "src/index.js"
compatibility_date = "2024-04-04"

# Esto sirve tu HTML, CSS y JS automáticamente
[assets]
directory = "./frontend/"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "bd-empresa"
database_id = "63af0b14-931f-45cd-bfb5-a06ef69906a0"

